### ISSUE TITLE
Player not working (JS console throws a "SyntaxError: Unexpected end of JSON input" error)

### ISSUE THREAD

**Issue by vrubiolo** [mrk-andreev/demo-tsplayer#4]
Hello there and thanks for making this demo available! I found it as I am looking for a graphical viewer for some Redis TS records. I had planned on trying it before plugging it my own Redis instance to graph their values.

I am having a hard time to make it work though: there is no proper graph displayed and the JS console is filled with "SyntaxError: Unexpected end of JSON input" errors. I guess some JSON format structure changed since you last tried the demo.

I am attaching a screenshot of how this looks. I am running via the Docker Compose environment you put, unmodified on Fedora 36. I have the same issue on Firefox 104.0.1 and Chromium 103.0.5060.114 (Official Build)

Would you be able to lend a hand here on what the issue might be? I can provide my logs as needed.

Thanks much!
![demo-ts-player-error](https://user-images.githubusercontent.com/8413245/190983754-8a8fd523-b6ea-4ec9-9178-43dccb0a0f60.png)
[demo-tsplayer-log.txt](https://github.com/mrk-andreev/demo-tsplayer/files/9597466/demo-tsplayer-log.txt)

**Comment by mrk-andreev** [comment]
Thank you for your feedback. I fixed this issue. Please, pull latest changes.

**Comment by vrubiolo** [comment]
Thanks for the quick reply!

I tried to pull from my existing repo but it looks like there is an issue w/ CRLF handling on some of the assets, prevening any pull (`gs` is my alias for `git status`, `gd` is for `git diff`, I had to use screenshots because of a copy-paste issue w/ my terminal emulator, sorry for that):
![git_status](https://user-images.githubusercontent.com/8413245/192800903-ff338a28-910c-437f-a5f8-f6e5b15f19d9.png)

![git_diff](https://user-images.githubusercontent.com/8413245/192800941-adede8b6-de06-469e-857d-1aa7569e9455.png)

Despite trying to `git reset --hard` or committing the changes and manually trying to excise the problematic commit, the changes would not go away and I had to reclone :disappointed: 

With a fresh repo, I can confirm the UI now can visualize the data after startup. 

Thanks for the quick fix, I will see to plug in my data then :+1:
